export const tagsDefine = [
  'html',
  'css',
  'nodemon',
  'javascript',
  'sintaxe',
  'typescript',
  'node.js',
  'node',
  'react.js',
  'react Native',
  'next.js',
  'mongodb',
  'web',
  'site',
  'testes',
  'teste',
  'jest',
  'vite',
  'vitest',
  'tdd',
  'linux',
  'mac',
  'windows',
  'mobile',
  'code',
  'prática',
  'pratica',
  'prática',
  'backend',
  'frontend',
  'fullstack',
  'full stack',
  'desktop',
  'reactnative',
  'front end',
  'front-end',
  'tutorial',
  'guia',
  'configuração',
  'instalação',
  'aula',
  'web site',
  'flexbox',
  'display grid',
  'responsive',
  'react js',
  'dicas',
  'dica',
  'tailwind',
  'organizar',
  'deploy',
  'storybook',
  'landing page',
  'landingpage',
  'hooks',
  'expo',
  'conceitos',
  'basico',
  'iniciantes',
  'iniciante',
  'introducao',
  'introdução',
  'avançado',
  'avancado',
  'intermediario',
  'intermediário',
  'mysql',
  'postgresql',
  'sql',
  'nosql',
  'criar',
  'criando',
  'ambiente',
  'sair do zero',
]

export const categoryOrder = [
  'lógica',
  'frontend',
  'backend',
  'mobile',
  'banco de dados',
  'teste',
  'ferramentas',
  'acessibilidade',
  'deploy',
]
export const subCategoryOrder = [
  {
    name: 'lógica',
    subcategories: ['lógica de programação'],
  },
  {
    name: 'frontend',
    subcategories: [
      'html',
      'css',
      'tailwindcss',
      'javascript',
      'typescript',
      'react.js',
      'next.js',
      'react native',
      'remix.js',
      'vue.js',
    ],
  },
  {
    name: 'backend',
    subcategories: ['node.js', 'nest.js', 'go', 'php', 'python'],
  },
  {
    name: 'mobile',
    subcategories: ['react native', 'flutter'],
  },
  {
    name: 'banco de dados',
    subcategories: ['mongodb', 'mysql', 'postgresql'],
  },
  {
    name: 'teste',
    subcategories: ['cypress.js', 'playwright', 'vitest', 'jest'],
  },
  {
    name: 'ferramentas',
    subcategories: ['terminal', 'git', 'vscode', 'docker'],
  },
  {
    name: 'acessibilidade',
    subcategories: ['acessibilidade'],
  },
  {
    name: 'deploy',
    subcategories: ['aws', 'digitalocean', 'vercel', 'netlify', 'railway', 'render'],
  },
]
